#!/usr/bin/env bash
#
# print 1 if playing, else 0


usage() {
    echo "usage: $(basename $0)" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

pid="$(vlc pid)" || exit
[[ -z $pid ]] && exit

out=$(osascript "${BASH_SOURCE[0]%/*}"/."${BASH_SOURCE[0]##*/}".applescript "$@") || exit
[[ -z "$out" ]] && out=0; echo $out
